### ISSUE TITLE
[Admin] Branching Option

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/TAOS-CI#239]
- [x] **Require branches to be up to date before merging**
This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take effect unless at least one status check is enabled (see below).

You have enabled that option, which requires to rebase EVERY PR whenever a PR is merged. Do you really need that option enabled?

**Comment by leemgs** [comment]
* Screenshot:
![image](https://user-images.githubusercontent.com/82404/45276694-cf745280-b4fe-11e8-98a8-bd353e32efe5.png)

**Comment by myungjoo** [comment]
So.. do you really need it? (why?)

**Comment by leemgs** [comment]
I have enabled this feature to test a PR with latest code as an experiment even though it is impractical in case of one branch structure. So it will be continued for a while.

**Comment by myungjoo** [comment]
Ok. I've got it.

**Comment by leemgs** [comment]
![tic_pkglist_domains_options_presets](https://user-images.githubusercontent.com/82404/46140496-3b3f1500-c28c-11e8-95e0-1bcd83da0c41.png)
