### ISSUE TITLE
[Discussion] Simple CD service for users

### ISSUE THREAD

**Issue by leemgs** [nnsuite/TAOS-CI#253]
**Is your feature request related to a problem? Please describe.**
Can we do provide up-to-date packages in real time ?
* CD: Continuous Deployment

**Describe the solution you'd like**
How can we effectively advertise cool features to users?
"No user, no software" 

For example, we can archive latest package files (.rpm) whenever we generate binary files from source code from Pull Request (PR).

**Describe alternatives you've considered**
Let's provide latest packages (e.g. .deb , .rpm)

**Additional context**
Need idea from others.

**Keywords**
github cd service

**Overall Flow**

![image](https://user-images.githubusercontent.com/82404/47061963-d170b600-d20e-11e8-886b-7dffd8f68134.png)

**Comment by leemgs** [comment]
### Case study: NNStreamer
* https://github.com/nnsuite/nnstreamer/issues/580

**Comment by leemgs** [comment]
## github deployment event
* https://developer.github.com/v3/repos/deployments/

Deployments are requests to deploy a specific ref (branch, SHA, tag). GitHub dispatches a deployment event that external services can listen for and act on when new deployments are created. 

Below is a simple sequence diagram for how these interactions would work.
![image](https://user-images.githubusercontent.com/82404/47063631-e3565700-d216-11e8-80d4-9a581eb02264.png)

**Comment by myungjoo** [comment]
For device development, the requirements for CD is:


- Package repository updates

    - Daily / Weekly / Stable might need to be separated.
    - Snapshot package releases.
    - OBS/Launchpad support (??)
    - (optional) Multi-version support? (LTS versions?) if we have multiple branches for LTS releases.

- OS image releases
