### ISSUE TITLE
Webhook handelr: Run "git clone" command once only for a PR

### ISSUE THREAD

**Issue by leemgs** [nnsuite/TAOS-CI#299]
The current TAOS-CI run "git clone" command twice whenever the pull request (PR) is submitted by contributors. We need to change the number of "git clone" commands from twice to once. 

* Before: Run "git clone" command per each module in the Jenkins. It's very naive. 
* Currently: TAOS-CI runs "git clone" command twice for (1) format  and (2) audit checker.

**Comment by leemgs** [comment]
* After (This ide is proposed by @ohsewon ) : 
   * run gateway.sh with a synchronous metod 
   * gateway.sh run  two checkers with an async method to avoid time out issue of webhook event.
      * run format checker (e.g., pr-format-async.sh)
      * run audit checker (e.g., pr-audit-async.sh)

**Comment by myungjoo** [comment]
To accelerate git clone, use "reference" option, refering a previously cloned repo (previous PR).

```
       --reference <repository>
           If the reference repository is on the local machine, automatically setup .git/objects/info/alternates to obtain objects from the reference repository. Using an already existing repository as an alternate will require fewer objects to be copied from the
           repository being cloned, reducing network and local storage costs.

           NOTE: see the NOTE for the --shared option, and also the --dissociate option.
```

This greately reduces git clone latencies.

**Comment by leemgs** [comment]
As you know, we have already used --reference to speed-up a git clone procedure.

**Comment by leemgs** [comment]
PR #300, #302, and #303 fix this issue.

**Comment by leemgs** [comment]
Completed.
