### ISSUE TITLE
Github has "Check" interface for PR.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/TAOS-CI#381]
![image](https://user-images.githubusercontent.com/1109011/48063788-6c0a5680-e209-11e8-842e-ef528637a643.png)

Maybe.. we can also utilize this new interface.

**Comment by leemgs** [comment]
Yes. A month ago, I saw that they try to link  each PR to the  existing CI infrastructure (e.g., Travis-Ci, Circle-CI, Appveyor,....)

**Comment by leemgs** [comment]
Let's close this issue.
