### ISSUE TITLE
[Feature/Broken Arrow] "Stop" button somewhere for PR checking?

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/TAOS-CI#382]
1. What about having a "button" or "link" at
either TAOS-CI webpage or PR-check github interface
that stops PR checking (and mark failed.)

So that we can STOP checking when we don't want to proceed.

Then,
2. Let's stop (kill processes) checking automatically when a PR is merged or closed
3. Let's stop (kill processes) overwritten with new commits. (this can be done by checking previous PR checks when a new PR comes to the queue)

## Action items (Proposal) 

- [x] Support  the global "Broken Arrow" facility
   - [x]  In case that the system is hang status due to too many PRs. #400 
- [x] Support the "**@broken arrow**" facility for author and reviewers
   - [x] Stop the existing PR build task in case that a PR is closed by author (or reviewers)
   - [ ] Stop the existing PR build task when author appends "**@broken arrow**" behind a PR title. 
- [x] Support a stop policy of build procedure
   - [x] Append a build stop policy (e.g., If Tizen (armv7l) is failed, Let's stop other build procedures immediately.)
   ```bash
   * The operation flow:
   Tizen(x86_64) ------> Tizen (armv7l) ------> Tizen (aarch64) ----> 
   Ubuntu (x86_64) ----> Yocto  (Poky/i586)
   ```

I welcome to any PR to complete action items above.

**Comment by leemgs** [comment]
Currently,  I am going to introduce "Broken Arrow" button via web page. 

Welcome to any PRs to improve the PR checking process. :)

**Comment by leemgs** [comment]
* Web UI (Proposal):

![image](https://user-images.githubusercontent.com/82404/48126116-b819d180-e2c3-11e8-8546-ab3793e1fcb0.png)

**Comment by ohsewon** [comment]
I like right-bottom thing.

**Comment by leemgs** [comment]
## Action items (Proposal) 

- [ ] Support  the global "Broken Arrow" facility
   - [ ]  In case that the system is hang status due to too many PRs.
- [ ] Support the "@broken arrow" facility for author and reviewers
   - [ ] Stop the existing PR build task in case that a PR is closed by author (or reviewers)
   - [ ] Stop the existing PR build taks when author appends "@broken arrow" behind a PR title.

**Comment by leemgs** [comment]
{Support the global "Broken Arrow" facility} is completed.
