### ISSUE TITLE
[AWS] Can we use Ubuntu ARM Server AMI on Amazon EC2

### ISSUE THREAD

**Issue by leemgs** [nnsuite/TAOS-CI#406]
We need to survey  again if we can use Ubuntu ARM Server AMI on Amazon EC2 to follow up ARM device.

**Comment by leemgs** [comment]
* History:
   * https://wiki.ubuntu.com/ARM/Server?_ga=2.259654796.766101751.1542014106-42344228.1542014106

**Comment by leemgs** [comment]
It seems that [Scaleway](https://www.scaleway.com/) is the first cloud hosting provider, to my knowledge, to offer ARM-based server. And it is cheap. Let’s try to create a Virtual Private Server (VPS) and configure it to run a website.

* Screenshot:

![image](https://user-images.githubusercontent.com/82404/48337910-9e9fcd80-e6a7-11e8-98d5-3e4623cf4d58.png)

**Comment by myungjoo** [comment]
This is very appealing to us. Let's try this.
1. Test "gbs" in armv8 server (you need to build gbs for armv8. they don't release one for arm devices)
2. Find a way to test arm CI test cases separately in arm servers.
3. You may first start with "daily/nightly" arm binary verification in arm servers w/o per-PR CI.

**Comment by myungjoo** [comment]
Reopening this until another issue opens up for arm vms.

**Comment by leemgs** [comment]
It's strange. I did not close this issue.

**Comment by leemgs** [comment]
## Chulwoo Park (AWS 박철우 부장)

- Senior Account Manager
- Amazon Web Services
- E: chulpark@amazon.com 
- M: +82 10 5410 5113

**Comment by myungjoo** [comment]
Ah... I thought that arm cloud plans were Amazon EC2.
If not, ....... I can't sure if we can use it (scaleway?) easily in time. (administrative issues that you know very well...)
