### ISSUE TITLE
Please add devel-nnsuite in gbs conf with highest priority.

### ISSUE THREAD

**Issue by myungjoo** [nnsuite/TAOS-CI#419]
Please add the RPM repo of Tizen:5.0:TAOS:UbuntuTools as the first (the highest priority) repo for gbs build.
So that we can override packages with different versions in Tizen:Base and Tizen:Unified.

This will allow us to workaround any glitches coming from Tizen:Base/Unified quickly.

**Comment by leemgs** [comment]
Since Nov-22 17:00
repos = repo.dev, repo.unified, repo.base

**Comment by myungjoo** [comment]
Thanks!
