### ISSUE TITLE
Links in the message generated by pr-format-misspelling.sh is wrong.

### ISSUE THREAD

**Issue by wooksong** [nnsuite/TAOS-CI#451]
Related comment in PR: https://github.com/nnsuite/TAOS-CI/pull/450#issuecomment-456719019

"TAOS-CI/ci" is duplicated:
http://nnsuite.mooo.com/TAOS-CI/ci/taos/TAOS-CI/ci/repo-workers/pr-checker/450-201901231750060.99059391021729-d251985f16d62d00222f4405068e93c989da0bf6/report/misspelling_result.txt.

I checked the code but found nothing wrong. 
It seems to be the environment variable issue.

**Comment by leemgs** [comment]
Thanks. This issue is generated by an incorrect setting of configuration file in the server. 

Fixed.
