### ISSUE TITLE
Dependency between groups

### ISSUE THREAD

**Issue by kparichay** [nnsuite/TAOS-CI#485]
The groups (format, audit etc) should have dependency between them, and a group should run only when its dependencies have passed. The dependency between the groups can be used for various purposes.

One simple example is: expensive groups depends on inexpensive groups. In our case, **audit group will depend on format group**. Hence, format group will first run as it has no dependency. If the format group passes, then audit group will run. If format group fails, audit group will not run (in this case, the PR has to be resubmitted anyway. The resources will be wasted if we do audit build check as the final result of TAOS-CI check is FAIL. This resource can be rather used efficiently for other PR checks).

**Comment by myungjoo** [comment]
> 
> 
> > If format group fails, audit group will not run (in this case, the PR has to be resubmitted anyway.
> 
> When the PR has to be resubmitted, The Out-Of-PR killer kills the existing PR(s) to do not work duplicated tasks.
> 
> If we want to support a method to save the system resources (e.g., CPU, Memory) for users that are using with a low-end computer, we can provide a group management via the configuration file.
> 
> For example,
> 
>     1. Append new policy to consider various situations.
>        
>        * Check if the format groups is failed
>        * Decide whether we want to continue next group (e.g., audit group) or not when the format group is failed.
>        * Specify an appropriate policy  after considering the hardware resource and the system overhead.
> 
>     2. Append dependency_policy_between_groups={0|11} in the config-environment.sh file.
> 
> 
> Please try to create a PR. :)

Since when did we have the bot reply with such complicated messages? I didn't know we've implemented such an AI already  😮

**Comment by leemgs** [comment]
> Since when did we have the bot reply with such complicated messages? 

The example showed how to implement the another policy  when we want to stop the next step (e.g., audit group) in case that the format group is failed. The bot has to execute the activities (w/o the complicated messages). 

> I didn't know we've implemented such an AI already 

In my case, I am satisfied with the existing operation flow. 
*  Even though the format group (=low cost) is failed, TAOS-CI runs the audit group (=high cost) continually.

**Comment by kparichay** [comment]
resolved with #494
