### ISSUE TITLE
[CPP Checker/Bug Report] dlopen/dlsym/dlclose memory leak

### ISSUE THREAD

**Issue by helloahn** [nnsuite/TAOS-CI#552]
I made a [pr at `nnstreamer-example`](https://github.com/nnsuite/nnstreamer-example/pull/70) and, in my opinion, I detected a bug.

Though `dlclose()` is called in the right way., the cppchecker reports a memory leak like below.
Please check it.

https://github.com/nnsuite/nnstreamer-example/blob/053f2545ac9e82c4eba38d155b200459dd00392e/Tizen.native/Application/src/main.c#L87-L117
```bash
 87 /**
 88  * @brief verify that the so file can be loaded properly
 89  */
 90 int
 91 verify_so_file (const char *filename)
 92 { 
 93   void *dlhandle;
 94   struct NNStreamer_custom_class *nnst_class;
 95   char *dlsym_error;
 96   
 97   dlhandle = dlopen (filename, RTLD_NOW);
 98   if (dlhandle == NULL) {
 99     dlog_print (DLOG_ERROR, "NNStreamerApp", "Unable to open so file.");
100     return -1;
101   }
102   
103   dlerror ();
104   nnst_class =
105       *((struct NNStreamer_custom_class **) dlsym (dlhandle,
106           "NNStreamer_custom"));
107   dlsym_error = dlerror ();
108   if (dlsym_error) {
109     dlog_print (DLOG_ERROR, "NNStreamerApp",
110         "Unable to read symbol from so file with error %s", dlsym_error);
111     dlclose (dlhandle);
112     return -1;
113   }
114   
115   dlclose (dlhandle);
116   return ML_ERROR_NONE;
117 }
```

Error Report
```bash
cppcheck_result.txt
=========================================================
[Tizen.native/v5.0/Application/src/main.c:112]: (error) Resource leak: dlhandle
[Tizen.native/v5.0/Application/src/main.c:116]: (error) Resource leak: dlhandle
```

**Comment by myungjoo** [comment]
Suggestion on Line 98 to avoid false-positives of cppcheck:
```
if (dlhandle == NULL) {
```
==>
```
if (!dlhandle) {
```

**Comment by myungjoo** [comment]
AH.. that didn't work.

**Comment by myungjoo** [comment]
Cppcheck 1.82 (ubuntu 18.04) does not have this problem. (16.04 has 1.72)

We may use Ubuntu-backports PPA to use more recent cppcheck. E.g., https://launchpad.net/~brcha/+archive/ubuntu/backports

**Comment by leemgs** [comment]
[SUMMARY] In this case, there are three approaches.
* Adding new version of CPPcheck - https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa
   * e.g., Ubuntu 16.04 does not provide the latest version of CPPcheck.
* Passing the CI-bot of the GitHub repository manually
* Disabling CPPcheck module in case of Ubuntu 16.04

**Comment by myungjoo** [comment]
In CI module, pass cppcheck if cppcheck version is < 1.82.
For our CI instance, let's update cppcheck with PPA backports if that does not require too much labor.
