### ISSUE TITLE
We want to hide "TAOS" name in the comments

### ISSUE THREAD

**Issue by DonghwanJeong** [nnsuite/TAOS-CI#592]
In the feature, There are a lot of the word "TAOS" in the message, so the first user(newbee) sees what is it.
We think that it is better to change another name by config file. Of course, "TAOS" is project name, but the word is better to remain only information side. This term is used in many location.

```
TAOS/pr-prebuild-cppcheck — Oooops. cppcheck is failed. Please, read cppcheck_result.txt for more details.
Details
TAOS/pr-prebuild-doxygen-tag — Oooops. The doxygen checker is failed. Please, write doxygen document in your code.
Details
TAOS/pr-prebuild-sloccount — Oooops. sloccount checker is failed because the check_result is not either 'success' or 'skip'.
```

**Comment by myungjoo** [comment]
Uh.. that's the name of the service/system. According to the license, you may change it in your fork, though.

**Comment by leemgs** [comment]
Improved. Thanks.
